install.packages("tidyverse")
install.packages("rmarkdown")
install.packages("httr")
install.packages("shinydashboard")
install.packages('leaflet')
install.packages('xaringan')
install.packages('revealjs')
install.packages('tinytex')
